[meta title:"SIR Rumor Dynamics" description:"Modeling the spread of rumors on social networks" /]

[Header
  title:"SIR Rumor Dynamics"
  subtitle:"Modeling the spread of rumors on social networks"
  author:"Ethan Anderson, Cole Chamberlin, Evan Frawley"
  authorLink:"https://github.com/evanfrawley/partisan-news-viz" /]

This is an Idyll file. Write text
as you please in here. To add interactivity,
you can add  different components to the text.

Here is how you can use a variable:

[var name:"exampleVar" value:5 /]

[Range min:0 max:10 value:exampleVar /]
[Display value:exampleVar /]

```js
var code = true;
```

And here is a custom component:

[CustomComponent /]

You can use standard html tags if a
component with the same name
doesn't exist.

* *markdown* syntax is supported.

[var name:"state" value:0 /]

[CustomD3Component /]
[FlowChart /]