[meta title:"SIR Rumor Dynamics" description:"Modeling the spread of rumors on social networks" /]

[var name:"sidePanelView" value:"initial" /]

[section className:"topSection"]

[waypoint onEnterViewFully:`sidePanelView = "initial"`]
[Header
  title:"Rumor Spreading Dynamics"
  subtitle:"Understanding Multiple Rumor Spreading Through SIR Models"
  authors:`[
      {name: "Evan Frawley", link: "https://github.com/evanfrawley"},
      {name: "Ethan Anderson", link: "https://github.com/aethanol"},
      {name: "Cole Chamberlin", link: "https://github.com/jessecoleman"}
    ]`
  /]
[p]
# Rumors

A rumor, in general, refers to an unverified account or explanation of events circulating from person to person and pertaining to an object, event, or issue of public concern. \[[link target:"_blank" href:"https://www.sciencedirect.com/science/article/pii/S037843711200934X#br000005"]1[/link]\]

Spreading rumors has many sociological causes, but well studied is its use as a form of social cognition, where people come across novel pieces of information, or rumors and share them with others as an attempt to reduce anxiety and uncertainty. This is especially found in termed ***dread*** rumors, which refer to some fearsome, or undesirable event. **These dread rumors are spread at a much higher rate than wish rumors** which denote a positive outlook on the rumor context. DiFonzo et al. showed how people come across a rumor, and in order to make sense of the information, they share these dread rumors with other people.

(Source: DiFonzo, P. B. and N. (2014). Problem in Social Interactions on the Internet : Solving Rumor As Social Cognition *, 67(1), 33–49.)

## Why are rumors important to study?
[/p]
# Simulating Rumor Transmission with SIR
[p]
SIR, or Susceptible, Infected, and Recovered is an epidemiological model which has been widely applied to rumoring theory, and the way that people spread pieces of information across social networks. (Daley and Kendall, Nekovee et al, and Zhao et al) Like vectors of disease, vectors of rumor too can be spread by contact between people in a social network.
In Daley and Kendall’s pioneering model, the population of people participating in a rumor is split into three distinct groups: people who are unaware of the rumor (ignorants), people who are actively spreading the rumor (spreaders), and people who are not spreading the rumor - either by debunking or just not participating (stiflers).

TODO: actually write about other studies.

This work was later expanded by Zhao, et al. who formalized a model better aligned with reality by taking individual choice into consideration (cite).
[/p]

[div onEnterViewFully:`sidePanelView = "flowchart"`]

δ is the probability that a spreader spontaneously loses interest in, or forgets about a rumor.

λ is the probability that an ignorant **turns into a spreader**.

1 - λ is the probability that an ignorant **turns into a stifler**.

η is the probability that a **spreader turns into a stifler** when contacting a *stifler*.

γ is the probability that a spreader **turns into a stifler** when contacting another *spreader*. Imagine the case when the two spreaders have differing versions of the same rumor; leading the spreader to question the rumor, where γ is restricted to be less than η.

γ is restricted to be less than η because it logically follows that an ignorant has a to have a higher probability of becoming a spreader than a stifler when interacting with a spreader, following the assumptions made in the above papers.
[/div]
[/waypoint]

[waypoint onEnterViewFully:`sidePanelView = "equations"`]
# Scale Free Networks

A scale-free network is a network which has a degree distribution that follows a power law. That is, there is an exponential relation between the degree of connectivity of a node and its frequency of occurrence in the network where the fraction P(x) of nodes in the network having connections to k other nodes is

[Equation]
P(k) ~ k^{-γ} = 1/k^γ
[/Equation]

where where γ is typically in the range 2 < γ < 3.

TODO: in d3 Explanation with a power-law graph. 1/x^2 where x axis is number of degrees, and y is proportion of nodes with that degree.
With dots at (¼, 2), (1/9, 3) (1/100, 10).
[/waypoint]

## Preferential Attachment
Barabási and Albert demonstrated that large scale networks self organize into scale-free states, regardless of the source of that network (cite). This follows the property of preferential attachment, or the principle of “the rich get richer”, where in a network the nodes with higher degree are likely to get a higher percentage of new node ties. More formally: the probability that a new node in a network will make a tie to any node is proportional to the degree of that node. This gives the property that local connectivity is free of scale.

## Social Networks
Applied to social networks, this might explain Milgram’s small world phenomena, where there are “six degrees of separation” between you and any other person in the United States. In this case, it is easy to see how people organize into tightly knit communities, with some connections between communities. Some people, however are connected to a larger number of communities like celebrities or politicians who act as hubs between many different communities.


[waypoint]
# Generating Scale-Free Networks
[p  onEnterViewFully:`sidePanelView = "psuedocode"`]
<TODO: cole write about how the networkx model is actually working? -- maybe add a visualization of generation??>

## Barabási–Albert model

<TODO: explain BA model>
To generate a social network, we utilize the Holme and Kim algorithm in the python package networkx. The algorithm is a slight modification of the BA network generation model. In this modification, there is an extra step when generating each random edge where there is a chance of generating an additional edge with one of its existing neighbors. It improves on BA by enabling a higher average degree of clustering, which allows us to simulate on a wider variety of graphs.
[/p]
[/waypoint]

[waypoint onEnterViewFully:`sidePanelView = "sliders"`]
[p]
# Density and Clustering Coefficient

## Graph parameters

[var name:"density" value:0.01 /]
[Range value:density min:0.01 max:0.02 step:0.0025 /]
Density: [Display value:density /]

[var name:"cluster" value:0.7 /]
[Range value:cluster min:0.5 max:1 step:0.1 /]
Clustering Coefficient: [Display value:cluster /]

## Rumor parameters

[var name:"lambda" value:0.8 /]
[Range value:lambda min:0 max:1 step:0.1 /]
Lambda: [Display value:lambda /]

[var name:"eta" value:0.6 /]
[Range value:eta min:0 max:1 step:0.1 /]
Eta: [Display value:eta /]

[var name:"gamma" value:0.3/]
[Range value:gamma min:0 max:1 step:0.1 /]
Gamma: [Display value:gamma /]

[var name:"delta" value:0.2 /]
[Range value:delta min:0 max:1 step:0.1 /]
Delta: [Display value:delta /]

[/p]
[/waypoint]
[/section]

[section]
[waypoint onEnterViewFully:`sidePanelView = "none"`]
[link target:"_blank" href:"http://jessecoleman.github.io/sir-rumor-viz/" ]Actual visualization![/link]
[/waypoint]
[/section]

[fixed]
[SidePanel view:sidePanelView gamma:gamma delta:delta eta:eta lambda:lambda cluster:cluster density:density /]
[/fixed]
